import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Link from "next/link";
import { AppProvider } from "./context/AppContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white shadow p-4">
        <div className="max-w-7xl mx-auto flex gap-20 justify-items-start items-center">
        <a href="/" className="text-xl font-bold text-indigo-600">THE INDIAN WALLSTREET</a>

        <div className="space-x-6">
        <Link href="/portfolio" className="text-gray-700 hover:text-indigo-600">PORTFOLIO</Link>
        <Link href="/sectors" className="text-gray-700 hover:text-indigo-600">SECTORS</Link>
        </div>
        </div>
        </nav>
        <AppProvider>
        {children}
        </AppProvider>
      </body>
    </html>
  );
}
